### ISSUE TITLE
The trigger should be out of the plugin itself

### ISSUE THREAD

**Issue by vonpupp** [roggan87/vim-bible#3]
Hello @roggan87,

Congratulations on your great plugin! I forked your repo and removed the first two lines:

```
nnoremap <leader>b y :call Bible()<CR>
vnoremap <leader>b y :call Bible(@*)<CR>
```

Since it was conflicting with another keystroke. I don't know anything about vimscript but I believe these type of configs should be outside of the code as `user` code.

Herewith an example of my config:

```
Bundle 'vonpupp/vim-bible'
let g:BibleTranslation = "nlt-se"
let g:BibleFormat = "\\4"
let g:BibleLocale = "en"
let g:BibleDelimiter = " "

nnoremap <leader>v y :call Bible()<CR>
vnoremap <leader>v y :call Bible(@*)<CR>
```

If you think this is an improvement that worth being included, I will be happy to create a PR for you.

**Comment by roggan87** [comment]
Hi,

Glad you like the plugin! Please update the readme accordingly (especially the installation part) and create a pull request. I'll gladly include the changes.

Blessings!

**Comment by vonpupp** [comment]
Amen! I have another suggestion @roggan87, but I prefer to wait until we are done with this one so I can open a new issue (and PR if applicable).

God bless you!
