### ISSUE TITLE
Support for multiple translations

### ISSUE THREAD

**Issue by vonpupp** [roggan87/vim-bible#5]
Hello @roggan87,

This is my first experience with vimscript, so I may be wrong or ignorant in how to do it right. As the `Bible()` function is implemented it uses global variables and it is not possible to use multiple translations.

Consider the case when you want to include verses near each other from different translations/versions of the bible, even different languages. The `Bible()` function would need to be refactored to be able to receive as parameters the translation version to be used, format, locale, etc.

I did this on [my fork]. However my solution has a caveat: all the parameters are mandatory, which is not very elegant. An example of use would be:
```
nnoremap <C-I>n y :call Bible("nlt-se", "\\4", "en", " ", 0)<CR>
nnoremap <C-I>k y :call Bible("KJV", "\\4", "en", " ", 1)<CR>
nnoremap <C-I>j y :call Bible("jfa-rc", "\\4", "en", " ", 0)<CR>
```

Further details are on the [commit message] itself. If you want I can PR my version, or if you prefer not to you can just link to my version which work for those cases. As you wish.

EDIT: Another thing to consider, I did not know how to use the equivalent of your config `vnoremap <leader>v y :call Bible(@*)<CR>` on my version. I guess this gets a passage from the cursor on visual mode without querying for it. I still need to work on that.

Blessings.

[my fork]: https://github.com/vonpupp/vim-bible/blob/develop/plugin/bible.vim#L11-L16
[commit message]: https://github.com/vonpupp/vim-bible/commit/b05692f68949e35ca5221fd288a07d100488af78

**Comment by roggan87** [comment]
Good point! It would be really useful to add the suggested parameters. I'm very new to vimscript as well, so let's help each other out here. If you make a pull request we can discuss the implementation there before accepting it.

**Comment by roggan87** [comment]
Yes, `vnoremap` means the mapping only applied to the visual mode, and `@*` passes the selection as an argument, so in your case this would be perfectly valid:

    nnoremap <C-I>n y :call Bible("nlt-se", "\\4", "en", " ", 0)<CR>
    vnoremap <C-I>n y :call Bible("nlt-se", "\\4", "en", " ", 0, @*)<CR>

**Comment by vonpupp** [comment]
Thank you for your explanation, that is what I thought. However, for some reason this doesn't work yet (only in visual mode). I will try to debug a little bit that part before the PR.

**Comment by vonpupp** [comment]
I updated the PR @roggan87, I hope it is better now. I included your first and last comment, thanks for noticing. Each of your comments has an answer also. That is the best code I could come up with my little (almost none) vimscript knowledge. I tried the plugin with all the documented examples and it seems to work fine, except for the visual mode which still do not work. Could you please check if it works for you? It should work.

Regards. God bless you.

**Comment by vonpupp** [comment]
Hello @roggan87, if you have any difficulties with merging the PR let me know and I will do a new one. I used git flow and I merged it to master before doing a PR, I should have done the PR directly from the branch. Sorry, newbie stuff.

**Comment by roggan87** [comment]
@vonpupp, I haven't had time to try your PR, I'm not sure when I'll get time either. Thanks for your contribution though, hopefully it'll get implemented sooner or later.

**Comment by roggan87** [comment]
I've merged your pull request, thanks for your contribution! One thing I changed was the order of the arguments. The order is now query, translation, format, locale, delimiter, omitModuleName. If query or translation is set to "", the user will be prompted for it.

**Comment by vonpupp** [comment]
Great, I will try it back. Thank you very much @roggan87. This is my first PR =)

Does the visual mode works for you?

**Comment by roggan87** [comment]
The visual mode works like a charm for me! If you come up with more improvements. let me know :)
